/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_squareup_jnisam_JNINew */

#ifndef _Included_com_squareup_jnisam_JNINew
#define _Included_com_squareup_jnisam_JNINew
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_squareup_jnisam_JNINew
 * Method:    getTian
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_squareup_jnisam_JNINew_getTian
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
