/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_squareup_jnisam_JNITest */

#ifndef _Included_com_squareup_jnisam_JNITest
#define _Included_com_squareup_jnisam_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_squareup_jnisam_JNITest
 * Method:    getHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_squareup_jnisam_JNITest_getHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
